<?php
/**
 * This file is part of SocialLogin4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 *  https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\SocialLogin4\Tests\Web;


use Eccube\Tests\Web\Admin\AbstractAdminWebTestCase;
use Eccube\Util\StringUtil;

class Auth0ControllerTest extends AbstractAdminWebTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testAuth0の設定をしていなかったらNotFound()
    {
        $this->client->request('GET', $this->generateUrl('auth0_connect'));
        self::assertTrue($this->client->getResponse()->isNotFound());
    }

    public function testAuth0の設定をしていたらリダイレクト()
    {
        $container = self::$kernel->getContainer();
        $envFile = $container->getParameter('kernel.project_dir') . '/.env';

        $env = file_get_contents($envFile);
        $env = StringUtil::replaceOrAddEnv($env, [
            'OAUTH_AUTH0_CLIENT_ID' => "dummy",
            'OAUTH_AUTH0_CLIENT_SECRET' => "dummy",
            'OAUTH_AUTH0_CUSTOM_DOMAIN' => "dummy"
        ]);
        file_put_contents($envFile, $env);

        $this->client->request('GET', $this->generateUrl('auth0_connect'));
        self::assertTrue($this->client->getResponse()->isRedirection());
    }
}
