<?php
/**
 * This file is part of SocialLogin4
 *
 * Copyright(c) Akira Kurozumi <info@a-zumi.net>
 *
 *  https://a-zumi.net
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\SocialLogin4\Tests\Security\Authenticator;


use Eccube\Entity\Customer;
use Eccube\Tests\EccubeTestCase;
use KnpU\OAuth2ClientBundle\Client\Provider\Auth0Client;
use KnpU\OAuth2ClientBundle\Security\Exception\FinishRegistrationException;
use Plugin\SocialLogin4\Security\Authenticator\Auth0Authenticator;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Core\Exception\AuthenticationException;

class Auth0AuthenticatorTest extends EccubeTestCase
{
    /**
     * @var Auth0Authenticator
     */
    protected $authenticator;

    /**
     * @var RouterInterface
     */
    protected $router;

    /**
     * @var SessionInterface
     */
    protected $session;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $container = self::$kernel->getContainer();

        $this->authenticator = new Auth0Authenticator(
            $container->get('knpu.oauth2.registry'),
            $container->get('doctrine.orm.default_entity_manager'),
            $container->get('router')
        );

        $this->router = $container->get('router');
        $this->session = $container->get('session');

    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testStart()
    {
        $response = $this->authenticator->start(new Request());
        self::assertTrue($response->isRedirect($this->router->generate('auth0_connect')));
    }

    public function testCheckCredentials()
    {
        $customer = new Customer();
        self::assertEquals(true, $this->authenticator->checkCredentials('', $customer));
    }

    public function testSupportsRememberMe()
    {
        self::assertEquals(true, $this->authenticator->supportsRememberMe());
    }

    public function testOnAuthenticationFailure_FinishRegistrationException()
    {
        $request = new Request();
        $request->setSession($this->session);

        $response = $this->authenticator->onAuthenticationFailure($request, new FinishRegistrationException([]));
        self::assertTrue($response->isRedirect($this->router->generate('entry')));
    }

    public function testOnAuthenticationFailure_AuthenticationException()
    {
        $request = new Request();
        $request->setSession($this->session);

        $response = $this->authenticator->onAuthenticationFailure($request, new AuthenticationException());
        self::assertTrue($response->isRedirect($this->router->generate('mypage_login')));
    }

    public function testOnAuthenticationSuccess()
    {
        $Customer = $this->createCustomer();
        $token = new UsernamePasswordToken($Customer, null, 'customer', ['ROLE_USER']);
        $response = $this->authenticator->onAuthenticationSuccess(new Request(), $token, 'customer');
        self::assertTrue($response->isRedirect($this->router->generate('mypage')));
    }

    public function testCreateAuthenticatedToken_customerToken()
    {
        $Customer = $this->createCustomer();
        $token = $this->authenticator->createAuthenticatedToken($Customer, 'customer');
        self::assertInstanceOf(UsernamePasswordToken::class, $token);
    }
}
