name: PHPStan
on: [workflow_dispatch, pull_request]

env:
  PLUGIN_CODE: Auth0
  PLUGIN_PACKAGE_NAME: 'ec-cube/auth0'

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        eccube-versions: [ '4.2', '4.3' ]
        php-versions: [ '8.1' ]
        database: [ 'mysql8' ]
        include:
          - database: mysql8
            database_url: mysql://root:password@127.0.0.1:3308/eccube_db
            database_server_version: 8
            database_charset: utf8mb4
    services:
      mysql8:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3308:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: kurozumi/eccube-plugin-phpstan@v1.0.1
        with:
          plugin-code: ${{ env.PLUGIN_CODE }}
          plugin-package-name: ${{ env.PLUGIN_PACKAGE_NAME }}
          eccube-versions: ${{ matrix.eccube-versions }}
          php-versions: ${{ matrix.php-versions }}
          database-url: ${{ matrix.database_url }}
          database-server-version: ${{ matrix.database_server_version }}
          database-charset: ${{ matrix.database_charset }}
          composer-command: 'composer config --no-plugins allow-plugins.php-http/discovery false'
